### ISSUE TITLE
Hotkey is reassigned automatically 

### ISSUE THREAD

**Issue by airborn** [davidz627/feedlyBackgroundArticles#1]
I've changed a hotkey to `h`. From time to time, without any interaction, this hotkey switches back to its default value `;`

**Comment by lowply** [comment]
@airborn same here, what browser are you using? I'm on Microsoft Edge `Version 93.0.961.47 (Official build) (x86_64)`.

`chrome.storage.sync.set` saves the value ([options.js#L12](https://github.com/davidz627/feedlyBackgroundArticles/blob/main/FeedlyBackground/options.js#L12)). The `sync` function is supposed to save the value across multiple devices that associated with your Google account, but I guess something isn't working as expected and when sync runs it somehow reset to the original character, `;`.

Ref: [chrome.storage - Chrome Developers](https://developer.chrome.com/docs/extensions/reference/storage/)

**Comment by airborn** [comment]
I'm on chrome, currently `Wersja 93.0.4577.82 (Oficjalna wersja) (64-bitowa)`

**Comment by davidz627** [comment]
looks like people are having this issue on all sorts of browsers. I didn't see it cause I don't dogfood this feature (I use the default - that's probably why I made it the default 😆 ).

I'm busy this weekend, but can look into it the next. If either of you are willing and able to do something earlier, please feel free to put up a PR to fix and I will review, merge, and push the new version! @airborn @lowply

**Comment by airborn** [comment]
So I've opened #2 with a probable fix but still haven't tested this. Is there an option to test this locally? Sorry if that's something obvious but I'm neither Chrome Extensions nor JS guy :P

EDIT: ok it was obvious :) Let me run it for a while and check the behaviour.

**Comment by lowply** [comment]
Thank you @airborn that's awesome. I've temporarily disabled the current version and installed the newer version from your branch, let's see if it fixes the issue 🤞🏻

**Comment by airborn** [comment]
I have had it running for 3 days now, not sure when but the shortcut got rewritten once again :( Will try to dig deeper.

**Comment by airborn** [comment]
My bad, I've made a stupid error in the code, please update the extension source

**Comment by davidz627** [comment]
this should be resolved in version 0.21, please update the extension if you haven't already. Thanks for reporting and the fix @airborn !

**Comment by airborn** [comment]
I might have stumped upon this bug once again. Perhaps this was related to browser update, not sure. WIll try to put more attention to this with the next updates.
